language: python
services:
  - docker

python:
  - "3.8"

install:
  - pip install -r requirements.txt

script:
  - docker build -t dpetrovych/nonopy:latest .
  - python -m unittest -v

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: main


