#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push dpetrovych/nonopy:latest

if [ -z ${TRAVIS_BUILD_NUMBER+x} ]; then # if TRAVIS_BUILD_NUMBER is set
    docker tag dpetrovych/nonopy:latest dpetrovych/nonopy:1.0.${TRAVIS_BUILD_NUMBER}
    docker push dpetrovych/nonopy:1.0.${TRAVIS_BUILD_NUMBER}
fi

